SGLANG_ENABLE_SPEC_V2=1 python -m sglang.launch_server \
    --model-path nvidia/Kimi-K2.5-NVFP4 \
    --tp 8 \
    --speculative-algorithm=EAGLE3 \
    --kv-cache-dtype fp8_e4m3 \
    --speculative-num-steps 3 \
    --speculative-eagle-topk 1 \
    --speculative-num-draft-tokens 4 \
    --speculative-draft-model-path lightseekorg/kimi-k2.5-eagle3 \
    --speculative-draft-attention-backend trtllm_mha \
    --reasoning-parser kimi_k2 \
    --tool-call-parser kimi_k2 \
    --trust-remote-code \
    --port 10001
